export const streetNames = [
  'Main Street',
  'High Street',
  'Park Avenue',
  'Church Road',
  'Oak Street',
  'Maple Avenue',
  'Cedar Lane',
  'Elm Street',
  'Pine Road',
  'Washington Boulevard',
  'Lakeview Drive',
  'Broadway',
  'Market Street',
  'Baker Street',
  'Sunset Boulevard',
  'Chestnut Avenue',
  'Grove Lane',
  'Hillside Drive',
  'Willow Street',
  'River Road',
  'Broad Street',
  'First Avenue',
  'Second Street',
  'Third Avenue',
  'Fourth Street',
  'Fifth Avenue',
  'Park Street',
  'Meadow Lane',
  'Acorn Lane',
  'Magnolia Drive',
  'Spruce Court',
  'Hickory Lane',
  'Victoria Road',
  'Rose Street',
  'Greenwood Avenue',
  'Birch Lane',
  'Linden Boulevard',
  'Manor Road',
  'Sycamore Lane',
  'Cherry Street',
  'Forest Drive',
  'Windsor Avenue',
  'Juniper Lane',
  'Hillcrest Avenue',
  'Cypress Road',
  'School Street',
  'Pearl Street',
  'Crescent Avenue',
  'Cottonwood Lane',
  'Columbia Street',
  'Cambridge Road',
  'Orchard Lane',
  'Garden Street',
  'Brookside Drive',
  'Holly Court',
  'Pennsylvania Avenue',
  'Chestnut Street',
  'Riverside Drive',
  'Spruce Street',
  'Willow Lane',
  'Meadowbrook Road',
  'Elmwood Avenue',
  'Winding Way',
  'Hickory Court',
  'Woodland Avenue',
  'Sunnybrook Lane',
  'Glenwood Drive',
  'Lincoln Street',
  'Franklin Avenue',
  'Poplar Road',
  'Magnolia Court',
  'Sycamore Street',
  'Pine Street',
  'Harrison Avenue',
  'Valley Road',
  'Victoria Street',
  'Beech Street',
  'Harmony Lane',
  'Rosewood Drive',
  'Birch Street',
  'Windsor Drive',
  'Hillside Avenue',
  'Cypress Lane',
  'Holly Street',
  'Cedar Street',
  'Park Lane',
  'Cambridge Street',
  'Meadow Lane',
  'Laurel Road',
  'Columbia Avenue',
  'Orchard Street',
  'Garden Lane',
  'Brookside Avenue',
  'Holly Lane',
  'Pennsylvania Street',
  'Cottonwood Street',
  'Spruce Lane',
  'Elm Street',
  'Winding Road',
  'Hickory Street',
  'Woodland Street',
  'Sunnybrook Avenue',
  'Glenwood Court',
  'Lincoln Lane',
  'Franklin Street',
  'Poplar Street',
  'Magnolia Street',
  'Sycamore Court',
  'Pine Lane',
  'Harrison Street',
  'Valley Street',
  'Victoria Lane',
  'Beech Lane',
  'Harmony Street',
  'Rosewood Avenue',
  'Birch Lane',
  'Windsor Street',
  'Hillside Lane',
  'Cypress Street',
  'Holly Avenue',
  'Cedar Lane',
  'Park Street',
  'Cambridge Lane',
  'Meadow Avenue',
  'Laurel Street',
  'Columbia Court',
  'Orchard Avenue',
  'Garden Court',
  'Brookside Street',
  'Holly Lane',
  'Pennsylvania Lane',
  'Cottonwood Avenue',
  'Spruce Street',
  'Elm Lane',
  'Winding Avenue',
  'Hickory Lane',
  'Woodland Street',
  'Sunnybrook Court',
  'Glenwood Lane',
  'Lincoln Avenue',
  'Franklin Lane',
  'Poplar Avenue',
  'Magnolia Court',
  'Sycamore Street',
  'Pine Lane',
  'Harrison Road',
  'Valley Avenue',
  'Victoria Lane',
  'Beech Street',
  'Harmony Lane',
  'Rosewood Drive',
  'Birch Court',
  'Windsor Street',
  'Hillside Avenue',
  'Cypress Lane',
  'Holly Street',
  'Cedar Road',
  'Park Avenue',
  'Cambridge Drive',
  'Meadow Lane',
  'Laurel Road',
  'Columbia Street',
  'Orchard Lane',
  'Garden Avenue',
  'Brookside Lane',
  'Holly Court',
  'Pennsylvania Avenue',
  'Cottonwood Street',
  'Spruce Lane',
  'Elm Street',
  'Winding Way',
  'Hickory Court',
  'Woodland Avenue',
  'Sunnybrook Lane',
  'Glenwood Drive',
  'Lincoln Street',
  'Franklin Avenue',
  'Poplar Road',
  'Magnolia Court',
  'Sycamore Street',
  'Pine Street',
  'Harrison Avenue',
  'Valley Road',
  'Victoria Street',
  'Beech Street',
  'Harmony Lane',
  'Rosewood Drive',
  'Birch Street',
  'Windsor Drive',
  'Hillside Avenue',
  'Cypress Lane',
  'Holly Street',
  'Cedar Street',
  'Park Lane',
  'Cambridge Street',
  'Meadow Lane',
  'Laurel Road',
  'Columbia Avenue',
  'Orchard Street',
  'Garden Lane',
  'Brookside Avenue',
  'Holly Lane',
  'Pennsylvania Street',
  'Cottonwood Street',
  'Spruce Lane',
  'Elm Street',
  'Winding Road',
  'Hickory Street',
  'Woodland Street',
  'Sunnybrook Avenue',
  'Glenwood Court',
  'Lincoln Lane',
  'Franklin Street',
  'Poplar Street',
  'Magnolia Street',
  'Sycamore Court',
  'Pine Lane',
  'Harrison Street',
  'Valley Street',
  'Victoria Lane',
  'Beech Lane',
  'Harmony Street',
  'Rosewood Avenue',
  'Birch Lane',
  'Windsor Street',
  'Hillside Lane',
  'Cypress Street',
  'Holly Avenue',
];

export const firstNames = [
  'Emma',
  'Liam',
  'Olivia',
  'Noah',
  'Ava',
  'Sophia',
  'Isabella',
  'Mia',
  'Charlotte',
  'Amelia',
  'Harper',
  'Evelyn',
  'Abigail',
  'Emily',
  'Elizabeth',
  'Mila',
  'Ella',
  'Avery',
  'Sofia',
  'Camila',
  'Aiden',
  'Jackson',
  'Lucas',
  'Caden',
  'Grayson',
  'Mason',
  'Liam',
  'Benjamin',
  'Jacob',
  'Michael',
  'William',
  'Alexander',
  'James',
  'Elijah',
  'Daniel',
  'Matthew',
  'Oliver',
  'Joseph',
  'Henry',
  'David',
  'Samuel',
  'Sebastian',
  'Gabriel',
  'Carter',
  'Jayden',
  'John',
  'Luke',
  'Anthony',
  'Isaac',
  'Dylan',
  'Wyatt',
  'Andrew',
  'Joshua',
  'Christopher',
  'Jack',
  'Julian',
  'Ryan',
  'Levi',
  'Nathan',
  'Caleb',
  'Hunter',
  'Christian',
  'Isaiah',
  'Thomas',
  'Aaron',
  'Lincoln',
  'Charles',
  'Eli',
  'Landon',
  'Connor',
  'Josiah',
  'Jonathan',
  'Cameron',
  'Jeremiah',
  'Mateo',
  'Adrian',
  'Hudson',
  'Robert',
  'Nicholas',
  'Brayden',
  'Nolan',
  'Easton',
  'Jordan',
  'Colton',
  'Evan',
  'Angel',
  'Asher',
  'Dominic',
  'Austin',
  'Leo',
  'Adam',
  'Jaxon',
  'Ian',
  'Cooper',
  'Justin',
  'Gavin',
  'Leo',
  'Jeremiah',
  'Xavier',
  'Josiah',
  'Harrison',
  'Jason',
  'Ezra',
  'Chase',
  'Kevin',
  'Zachary',
  'Tyler',
  'Axel',
  'Eric',
  'Micah',
  'Ayden',
  'Jameson',
  'Brandon',
  'Adam',
  'Jonathan',
  'Patrick',
  'Nathaniel',
  'Cole',
  'Dylan',
  'Owen',
  'Henry',
  'Eli',
  'Bryan',
  'Caleb',
  'Max',
  'Carson',
  'Leo',
  'Ian',
  'Elias',
  'Alex',
  'Jesus',
  'Robert',
  'Samuel',
  'Giovanni',
  'David',
  'Alex',
  'Ezekiel',
  'Luca',
  'Anthony',
  'Cooper',
  'Blake',
  'Bentley',
  'Xander',
  'Edward',
  'Brody',
  'Axel',
  'Finn',
  'Andrew',
  'Roman',
  'Joseph',
  'Miles',
  'Xavier',
  'Tyler',
  'Hudson',
  'Camden',
  'Tristan',
  'Jake',
  'Declan',
  'George',
  'Felix',
  'Dawson',
  'Jordan',
  'Victor',
  'Greyson',
  'Emmanuel',
  'Cole',
  'Braxton',
  'Levi',
  'Ian',
  'Carson',
  'Maxwell',
  'Eli',
  'Ryker',
  'Elias',
  'Colin',
  'Maximus',
  'Roman',
  'Brantley',
  'Bryson',
  'Brody',
  'Reid',
  'Bennett',
  'Abel',
  'Derek',
  'Silas',
  'Kingston',
  'Ezekiel',
  'Jayce',
  'Hayden',
  'Jude',
  'Parker',
  'Joel',
  'Lorenzo',
  'Kaiden',
  'Erick',
  'Jesse',
  'Patrick',
  'Emmanuel',
  'Sean',
  'Bradley',
];

export const lastNames = [
  'Smith',
  'Johnson',
  'Williams',
  'Jones',
  'Brown',
  'Davis',
  'Miller',
  'Wilson',
  'Taylor',
  'Clark',
  'Hall',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Hill',
  'Scott',
  'Green',
  'Adams',
  'Baker',
  'Harris',
  'Thomas',
  'Lee',
  'Lewis',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Allen',
  'Hall',
  'Walker',
  'White',
  'Anderson',
  'Thomas',
  'Clark',
  'Wright',
  'Martin',
  'Thompson',
  'Parker',
  'Wood',
  'Lewis',
  'Green',
  'Baker',
  'Adams',
  'Mitchell',
  'Hall',
  'Turner',
  'Carter',
  'Campbell',
  'Davis',
  'Evans',
  'Collins',
  'Stewart',
  'Morris',
  'Rogers',
  'Reed',
  'Cook',
  'Morgan',
  'Murphy',
  'Gray',
  'Rogers',
  'Cooper',
  'Bryant',
  'Richardson',
  'Cox',
  'Howard',
  'Ward',
  'Peterson',
  'Jenkins',
  'Watson',
  'Bennett',
  'Henderson',
  'Robinson',
  'Perry',
  'Sanders',
  'Sullivan',
  'Simmons',
  'Ward',
  'Foster',
  'Gonzalez',
  'Barnes',
  'Fisher',
  'Russell',
  'Cruz',
  'Marshall',
  'Butler',
  'Hamilton',
  'Stewart',
  'Graham',
  'Patterson',
  'Morrison',
  'Bell',
  'Reed',
  'Ferguson',
  'Stevens',
  'Murray',
  'Wells',
  'Bryant',
  'Dunn',
  'Hansen',
  'Day',
  'Henry',
  'Berry',
  'Perkins',
  'Hudson',
  'Spencer',
  'Rice',
  'Andrews',
  'Matthews',
  'Simpson',
  'Crawford',
  'Stevens',
  'Mendoza',
  'Webb',
  'Sims',
  'White',
  'Cooper',
  'Burton',
  'Dean',
  'Warren',
  'Fox',
  'Cole',
  'Garrett',
  'Austin',
  'Reyes',
  'Pearson',
  'Mitchell',
  'Berry',
  'Harrington',
  'Lowe',
  'Fletcher',
  'Andrews',
  'Walters',
  'Burns',
  'Garza',
  'Morrison',
  'Chavez',
  'Sparks',
  'Franklin',
  'George',
  'Carpenter',
  'Little',
  'Little',
  'Banks',
  'Sandoval',
  'McDonald',
  'Bass',
  'Shaw',
  'Carr',
  'Townsend',
  'Snyder',
  'Morales',
  'Nichols',
  'Wilkins',
  'Harrington',
  'Guzman',
  'Gibson',
  'Cain',
  'Ellis',
];
